import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,GraduationCap,ClipboardCheck,FileText,BarChart3,Sun,Moon,Monitor,LogOut,Menu,X,Search} from 'lucide-react';
import './styles.css';

const API='http://localhost:5000/api';
const modules=[['dashboard','Dashboard',LayoutDashboard],['students','Students',Users],['faculty','Faculty',GraduationCap],['attendance','Attendance',ClipboardCheck],['results','Examinations',FileText],['reports','Reports',BarChart3]];
function App(){
 const [theme,setTheme]=useState(localStorage.theme||'auto'); const [page,setPage]=useState('dashboard'); const [mobile,setMobile]=useState(false); const [data,setData]=useState({students:0,faculty:0,attendanceRecords:0,resultRecords:0});
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 useEffect(()=>{const t=localStorage.token;if(!t)return;fetch(API+'/dashboard',{headers:{Authorization:'Bearer '+t}}).then(r=>r.ok?r.json():null).then(x=>x&&setData(x)).catch(()=>{})},[]);
 const logout=()=>{localStorage.removeItem('token');location.reload()};
 return <div className="app"><aside className={mobile?'open':''}><div className="brand"><div className="logo">O</div><div><b>OCMS</b><small>College Management</small></div><button className="icon mobileClose" onClick={()=>setMobile(false)}><X/></button></div><nav>{modules.map(([id,label,Icon])=><button className={page===id?'active':''} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={19}/>{label}</button>)}</nav><div className="sidebarBottom"><div className="theme"><span>Theme</span><div>{[['light',Sun],['dark',Moon],['auto',Monitor]].map(([v,I])=><button className={theme===v?'chosen':''} onClick={()=>setTheme(v)} title={v}><I size={16}/></button>)}</div></div><button className="logout" onClick={logout}><LogOut size={18}/> Sign out</button></div></aside>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<main><header><button className="icon menu" onClick={()=>setMobile(true)}><Menu/></button><div><span className="eyebrow">ONLINE COLLEGE MANAGEMENT</span><h1>{modules.find(x=>x[0]===page)?.[1]||'Dashboard'}</h1></div><div className="headerActions"><div className="search"><Search size={17}/><input placeholder="Search anything..."/></div><div className="avatar">A</div></div></header>{page==='dashboard'?<Dashboard data={data}/>:<Module page={page}/>}</main></div>}
function Dashboard({data}){return <section className="content"><div className="welcome"><div><span className="pill">Academic year 2026–27</span><h2>Good afternoon, Administrator 👋</h2><p>Here’s what’s happening across your college today.</p></div><button className="primary">+ Add record</button></div><div className="cards"><Stat icon={Users} label="Total Students" value={data.students}/><Stat icon={GraduationCap} label="Faculty Members" value={data.faculty}/><Stat icon={ClipboardCheck} label="Attendance Records" value={data.attendanceRecords}/><Stat icon={FileText} label="Exam Results" value={data.resultRecords}/></div><div className="grid"><div className="panel"><div className="panelHead"><div><b>Quick actions</b><span>Frequently used tools</span></div></div><div className="quick">{modules.slice(1,5).map(([id,label,I])=><button onClick={()=>location.hash=id}><I/><b>{label}</b><small>Manage {label.toLowerCase()}</small></button>)}</div></div><div className="panel"><div className="panelHead"><div><b>System overview</b><span>Core modules enabled</span></div></div><div className="list">{modules.slice(1).map(([_,label,I],i)=><div><span className="mini"><I size={16}/></span><b>{label}</b><span className="status">Active</span></div>)}</div></div></div></section>}
function Stat({icon:Icon,label,value}){return <div className="stat"><span className="statIcon"><Icon size={20}/></span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Module({page}){const labels={students:['Student Management','Manage student profiles, enrollment and academic details.'],faculty:['Faculty Management','Manage faculty profiles, departments and designations.'],attendance:['Attendance Management','Record and review student attendance.'],results:['Examinations & Results','Manage examinations, marks and grades.'],reports:['Reports & Analytics','Review operational data and generate reports.']};const [title,desc]=labels[page];return <section className="content"><div className="moduleHero"><span className="pill">Module</span><h2>{title}</h2><p>{desc}</p><button className="primary">+ Add new</button></div><div className="panel empty"><div className="emptyIcon">{page==='students'?'👨‍🎓':page==='faculty'?'👩‍🏫':page==='attendance'?'✓':page==='results'?'📄':'📊'}</div><h3>Ready to manage {title.toLowerCase()}</h3><p>The MERN API is connected to this module. Add records to start building your college data.</p></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
